SocialMedia/urls.py
from django.contrib import admin
from django.urls import path , include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls', namespace= 'home')),
    path('account/' , include('account.urls' , namespace= 'account'))
]

account/urls.py
from django.urls import path
from . import views



app_name = 'account'


urlpatterns = [
    path('register/' , views.UserRegisterView.as_view() , name='register'),
    path('login/' , views.UserLoginView.as_view() , name='Userlogin'),
    path('logout/' , views.UserLogoutView.as_view() , name='Userlogout'),
    path('profile/<int:user_id>' , views.UserProfileView.as_view() , name='userprofile'),
    path('follow/<int:user_id>' , views.UserFollowView.as_view() , name='user-follow'),
    path('unfollow/<int:user_id>' , views.UserUnfollowView.as_view() , name='user-unfollow')
]

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('home' , views.HomeView.as_view() , name='home'),
    path('post/<int:id>/<slug:slug>' , views.PostDetailView.as_view() , name='post-detail'),
    path('post/delete/<int:post_id>' , views.PostDeleteView.as_view() , name='post-delete'),
    path('post/update/<int:post_id>' , views.PostUpdateView.as_view() , name='post-update'),
    path('post/create' , views.PostCreateView.as_view() , name='post-create'),
    path('reply/<int:post_id>/<int:comment_id>' , views.ReplyView.as_view() ,name='reply'),
    path('like/<int:post_id>' , views.LikeView.as_view() , name='like')
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    body = models.TextField(max_length=400)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.slug
    
    def get_absolute_url(self):
        return reverse("home:post-detail", args=(self.id , self.slug))
    
class Vote(models.Model):

    user = models.ForeignKey(User , on_delete=models.CASCADE , related_name="uvotes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE , related_name="pvote")

    def __str__(self):

        return f'{self.user} like {self.post}'

home/forms.py
from django import forms
from .models import Post



class PostUpdateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('body',)

class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('body',)

home/views.py
from django.shortcuts import get_object_or_404, render , redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import Post , Vote
from .forms import PostUpdateForm , PostCreateForm
from comments.forms import CommentForm , CommentReplyForm
from comments.models import Comment
# Create your views here.


class HomeView(View):

    def get(self , request):
        posts = Post.objects.all()
        return render(request , 'home/index.html' , {'posts':posts})

class PostDetailView(View):

    def setup(self , request , *args , **kwargs):
        self.post_instance = Post.objects.get(id = kwargs['id'] , slug = kwargs['slug'])
        return super().setup(request , *args , **kwargs)
    comment_form = CommentForm
    reply_form = CommentReplyForm
    def get(self , request, *args , **kwargs):
        post = self.post_instance
        comments = post.pcomments.filter(is_reply = False)
        return render(request , 'home/post-detail.html' , {'post':post , 'comments':comments ,
                                                            'form':self.comment_form , 'reply_form' : self.reply_form })
    method_decorator(login_required)
    def post(self , request , *args , **kwargs):
        form = self.comment_form(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request , 'comment successfully')
            return redirect('home:post-detail' , self.post_instance.id , self.post_instance.slug)
        else:
            messages.error(request , 's.th is wrong')

class PostDeleteView(LoginRequiredMixin , View):

    def get(self , request , post_id):
        post = Post.objects.get(id = post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success( request , 'Post deleted successfully' , 'success')
        else:
            messages.error( request , 'you are not the owner' , 'error')

        return redirect('home:home')

class PostUpdateView(LoginRequiredMixin , View):

    form_class = PostUpdateForm

    def setup(self , request , *args, **kwargs):
         self.post_instance = Post.objects.get(id = kwargs['post_id'])
         super().setup(request , *args , kwargs)
    
    def dispatch(self , request ,*args, **kwargs):
        
        post = self.post_instance

        if not request.user.id == post.user.id:
            messages.error( request , 'ypu are not the owner' 'danger')
            return redirect('home:home')
        return super().dispatch(request , *args , **kwargs)
    def get(self, request , *args , **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request , 'home/update.html' , {'form':form})
    
    def post(self, request , *args , **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST , instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30]) 
            new_post.save()
            messages.success(request , 'you updated post successfuly' , 'success')
            return redirect('home:post-detail' ,  post.id , post.slug )
        
class PostCreateView(LoginRequiredMixin , View):
    
    form_class = PostCreateForm
    
    def get(self, request , *args , **kwargs):
        
        form = self.form_class
        print(form)
        return render( request , 'home/create.html' , {'form':form})
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.user = request.user
            print(new_post)
            new_post.save()
            messages.success(request , 'post created' , 'success')
            return redirect('home:home')
        
class ReplyView(LoginRequiredMixin , View):

    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Post , id = post_id)
        comment = get_object_or_404(Comment , id = comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            new_reply = form.save(commit=False)
            new_reply.user = request.user
            new_reply.is_reply = True
            new_reply.post = post
            new_reply.comment = comment
            messages.success(request , 'comment added' , 'success')
        return redirect(request , 'home:post-detail' , post.id , post.slug)

class LikeView(LoginRequiredMixin , View):
    

    def get(self, request, post_id):

        post = get_object_or_404(Post , id = post_id)
        like = Vote.objects.filter(post = post_id)
        if like.exists():
            messages.error(request, 'you have liked this post', 'danger')
        else:
            Vote.objects.create(post=post , user=request.user)
            messages.success(request , 'you liked this post' , 'success')
        return redirect('home:post-detail' , post.id , post.slug )

home/templates/home/create.html
{% extends 'base.html' %}



{% block content %}

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="create"name="" id="">
    </form>


{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}


{% block content %}

<div class="card">
    {% for post in posts %}
    <a href="{% url 'home:post-detail'  post.id post.slug %} " class="card-bosy">{{ post.body }}</a>
    {% endfor %}
</div>

{% endblock %}

home/templates/home/post-detail.html
{% extends 'base.html' %}

{% block content %}

    {% if request.user.id == post.user.id %}

    <a class="btn btn-danger" href="{% url 'home:post-delete' post.id %}">Delete</a>
    <a class="btn btn-info" href="{% url 'home:post-update' post.id %}">Delete</a>
    {% endif %}
    <p> <a href="{% url 'account:userprofile' post.user.id %}">{{ post.user }} </a></p>

    <p>{{ post.body }}</p>>

    {% if request.user.is_authenticated %}
    <a href="{% url 'home:like' post.id %}" class="btn btn-primary col-md-2 ">like</a>
    <br>
    <hr/>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="send" name="" id="">
    </form><br>

    {% else %}

    <p>you should login to comment</p>

    {% endif %}

    {% for comment in comments %}

    <div class = 'card bg-dark text-white p-3'>
        <p class="card-header">{{ comment.user }} | {{ comment.created|timesince }} </p>
        <p class="'card-body">{{ comment.body }}</p>


        {% if request.user.is_authenticated %}

        <form action="{% url 'home:reply' post.id comment.id %}" method="POST">
            {% csrf_token %}
            {{ reply_form.as_p }}
        </form>

        {% endif %}
        {% for reply in comment.rcomment.all %}
            <p class="bg-primary p-3 margin-2" >{{ reply.user }}</p><br>{{ reply.body }}
        {% endfor %}
    </div><br>

    {% empty %}
        <p>no comment yet</p>
    {% endfor %}




{% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}



{% block content %}

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update"name="" id="">
    </form>


{% endblock %}