SocialMedia/urls.py
from django.contrib import admin
from django.urls import path , include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls', namespace= 'home')),
    path('account/' , include('account.urls' , namespace= 'account'))
]

account/urls.py
from django.urls import path
from . import views



app_name = 'account'


urlpatterns = [
    path('register/' , views.UserRegisterView.as_view() , name='register'),
    path('login/' , views.UserLoginView.as_view() , name='Userlogin'),
    path('logout/' , views.UserLogoutView.as_view() , name='Userlogout'),
    path('profile/<int:user_id>' , views.UserProfileView.as_view() , name='userprofile'),
    path('follow/<int:user_id>' , views.UserFollowView.as_view() , name='user-follow'),
    path('unfollow/<int:user_id>' , views.UserUnfollowView.as_view() , name='user-unfollow')
]

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('home' , views.HomeView.as_view() , name='home'),
    path('post/<int:id>/<slug:slug>' , views.PostDetailView.as_view() , name='post-detail'),
    path('post/delete/<int:post_id>' , views.PostDeleteView.as_view() , name='post-delete'),
    path('post/update/<int:post_id>' , views.PostUpdateView.as_view() , name='post-update'),
    path('post/create' , views.PostCreateView.as_view() , name='post-create'),
    path('reply/<int:post_id>/<int:comment_id>' , views.ReplyView.as_view() ,name='reply'),
    path('like/<int:post_id>' , views.LikeView.as_view() , name='like')
]

templates/inc/messages.html
{% if messages %}

    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}" >{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
            {% if request.user.is_authenticated %}
            <a class="nav-link active" href="{% url 'account:Userlogout' %}">logout</a>
            <a class="nav-link active" href="{% url 'account:userprofile' request.user.id %}">profile</a>
            {% else %}
            <a class="nav-link active" href="{% url 'account:register' %}">register</a>
            <a class="nav-link active" href="{% url 'account:Userlogin' %}">login</a>
            {% endif %}
          </li>
      </div>
    </div>
  </nav>